### ISSUE TITLE
MissingPluginException for plugins.flutter.io/firebase_livestream_ml_vision0 (Only iOS)

### ISSUE THREAD

**Issue by prabel** [rishab2113/firebase_livestream_ml_vision#2]
Hi,
I tried to use this example - but every time I receive this exception 

```
The following MissingPluginException was thrown while activating platform stream on channel
plugins.flutter.io/firebase_livestream_ml_vision0:
MissingPluginException(No implementation found for method listen on channel
plugins.flutter.io/firebase_livestream_ml_vision0)
flutter:
When the exception was thrown, this was the stack:
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:504:29)
<asynchronous suspension>
#6      FirebaseVision.initialize (package:firebase_livestream_ml_vision/src/firebase_vision.dart:235:10)
<asynchronous suspension>
#7      _MyHomePageState._initializeCamera (package:example/src/example.dart:25:13)
<asynchronous suspension>
#8      _MyHomePageState.initState (package:example/src/example.dart:19:5)
```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G87, locale pl-PL)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.35.0)

**Comment by rishabnayak** [comment]
Yes, I have seen this issue - in fact I'm facing it too; I'm working on a fix but I'm not getting anywhere with it yet. You're welcome to open a PR if you can figure out a fix.

**Comment by voxoidtech** [comment]
was this ever resolved
